"""
HTML Report Generator for llm-testkit.

Generates clean, shareable HTML reports that QA managers and
non-technical stakeholders can read and act on.
"""

import html as html_mod
from datetime import datetime
from pathlib import Path

REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>llm-testkit Report - {title}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: #f5f7fa; color: #1a1a1a;
  }}
  .header {{ background: #1e3a5f; color: white; padding: 24px 40px; }}
  .header h1 {{ font-size: 24px; font-weight: 700; }}
  .header p {{ font-size: 14px; opacity: 0.7; margin-top: 4px; }}
  .container {{ max-width: 1100px; margin: 0 auto; padding: 32px 40px; }}
  .summary {{
    display: grid; grid-template-columns: repeat(4, 1fr);
    gap: 16px; margin-bottom: 32px;
  }}
  .summary-card {{
    background: white; border-radius: 8px; padding: 20px;
    border-left: 4px solid #2e75b6;
    box-shadow: 0 1px 4px rgba(0,0,0,0.08);
  }}
  .summary-card.fail {{ border-left-color: #dc3545; }}
  .summary-card.warn {{ border-left-color: #fd7e14; }}
  .summary-card.pass {{ border-left-color: #28a745; }}
  .summary-card .number {{ font-size: 36px; font-weight: 700; color: #1e3a5f; }}
  .summary-card.fail .number {{ color: #dc3545; }}
  .summary-card.pass .number {{ color: #28a745; }}
  .summary-card .label {{ font-size: 13px; color: #666; margin-top: 4px; }}
  .section {{
    background: white; border-radius: 8px; padding: 24px;
    margin-bottom: 24px;
    box-shadow: 0 1px 4px rgba(0,0,0,0.08);
  }}
  .section h2 {{
    font-size: 18px; font-weight: 600;
    margin-bottom: 16px; color: #1e3a5f;
  }}
  .badge {{
    display: inline-block; padding: 3px 10px;
    border-radius: 12px; font-size: 12px; font-weight: 600;
  }}
  .badge.critical {{ background: #ffe0e0; color: #c00; }}
  .badge.high {{ background: #fff3cd; color: #856404; }}
  .badge.medium {{ background: #d1ecf1; color: #0c5460; }}
  .badge.low {{ background: #d4edda; color: #155724; }}
  .badge.pass {{ background: #d4edda; color: #155724; }}
  .badge.fail {{ background: #ffe0e0; color: #c00; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 14px; }}
  th {{
    background: #1e3a5f; color: white;
    padding: 10px 14px; text-align: left; font-weight: 600;
  }}
  td {{ padding: 10px 14px; border-bottom: 1px solid #eee; vertical-align: top; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:nth-child(even) {{ background: #f9f9f9; }}
  .prompt-text {{
    font-family: monospace; font-size: 12px; color: #333;
    background: #f5f5f5; padding: 4px 8px;
    border-radius: 4px; max-width: 400px;
    word-break: break-word;
  }}
  .response-text {{ font-size: 12px; color: #555; max-width: 350px; word-break: break-word; }}
  .risk-bar {{
    height: 12px; background: #eee; border-radius: 6px;
    overflow: hidden; margin-top: 8px;
  }}
  .risk-fill {{ height: 100%; border-radius: 6px; }}
  .footer {{ text-align: center; color: #999; font-size: 12px; padding: 24px; }}
</style>
</head>
<body>
<div class="header">
  <h1>llm-testkit - {title}</h1>
  <p>Generated: {generated_at} &nbsp;|&nbsp; Tool: llm-testkit v0.1.0</p>
</div>
<div class="container">
  {content}
</div>
<div class="footer">
  Generated by <strong>llm-testkit</strong>
  - github.com/tenypeter007/llm-testkit
</div>
</body>
</html>"""


def generate_redteam_report(result, output_path: str):
    """Generate an HTML red team report from a RedTeamResult."""
    from llm_testkit.redteam.suite import SEVERITY_MAP

    esc = html_mod.escape  # shorthand for escaping user content

    # Summary cards
    risk_color = (
        "#28a745" if result.risk_score <= 3
        else "#fd7e14" if result.risk_score <= 6
        else "#dc3545"
    )
    risk_pct = int((result.risk_score / 10) * 100)

    summary = f"""
    <div class="summary">
      <div class="summary-card">
        <div class="number">{result.total_prompts}</div>
        <div class="label">Total Prompts Run</div>
      </div>
      <div class="summary-card {'fail' if result.vulnerability_count > 0 else 'pass'}">
        <div class="number">{result.vulnerability_count}</div>
        <div class="label">Vulnerabilities Found</div>
      </div>
      <div class="summary-card
        {'pass' if result.vulnerability_count == 0 else ''}">
        <div class="number">{result.total_prompts - result.vulnerability_count}</div>
        <div class="label">Tests Passed</div>
      </div>
      <div class="summary-card
        {'fail' if result.risk_score >= 7 else 'warn' if result.risk_score >= 4 else 'pass'}">
        <div class="number">{result.risk_score}/10</div>
        <div class="label">Risk Score</div>
        <div class="risk-bar">
          <div class="risk-fill" style="width:{risk_pct}%; background:{risk_color};"></div>
        </div>
      </div>
    </div>"""

    # Results by category
    cat_rows = ""
    for cat, data in result.results_by_category.items():
        total = data["passed"] + data["failed"]
        pass_rate = int(data["passed"] / total * 100) if total else 0
        status = "pass" if data["failed"] == 0 else "fail"
        severity = SEVERITY_MAP.get(cat, "medium")
        cat_name = esc(cat.replace('_', ' ').title())
        cat_rows += f"""
        <tr>
          <td><strong>{cat_name}</strong></td>
          <td><span class="badge {severity}">{severity.upper()}</span></td>
          <td>{total}</td>
          <td>{data['failed']}</td>
          <td><span class="badge {status}">{pass_rate}% pass</span></td>
        </tr>"""

    category_table = f"""
    <div class="section">
      <h2>Results by Category</h2>
      <table>
        <tr><th>Category</th><th>Severity</th>
        <th>Prompts</th><th>Failures</th><th>Pass Rate</th></tr>
        {cat_rows}
      </table>
    </div>"""

    # Failed prompts detail
    if result.failed_prompts:
        fail_rows = ""
        for f in result.failed_prompts[:50]:  # Cap at 50 for readability
            severity = f.get("severity", "medium")
            prompt = esc(f.get("prompt", ""))
            response = esc(f.get("response", f.get("error", "")))
            category = esc(f.get("category", "").replace('_', ' ').title())
            fail_rows += f"""
            <tr>
              <td><span class="badge {severity}">{severity.upper()}</span></td>
              <td>{category}</td>
              <td><div class="prompt-text">{prompt}</div></td>
              <td><div class="response-text">{response}</div></td>
            </tr>"""

        failures_section = f"""
        <div class="section">
          <h2>Vulnerability Details ({len(result.failed_prompts)} found)</h2>
          <table>
            <tr><th>Severity</th><th>Category</th><th>Prompt</th><th>Response</th></tr>
            {fail_rows}
          </table>
        </div>"""
    else:
        failures_section = """
        <div class="section">
          <h2>No Vulnerabilities Found</h2>
          <p style="color:#28a745; font-weight:600;">All red team tests passed successfully.</p>
        </div>"""

    content = summary + category_table + failures_section

    html = REPORT_TEMPLATE.format(
        title="Red Team Report",
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        content=content,
    )

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
